
services:
  luanti-server:
    image: linuxserver/luanti:latest
    container_name: luanti-voxelibre-server
    restart: unless-stopped
    ports:
      - "30000:30000/udp"
    volumes:
      - ./server/config/luanti.conf:/config/.minetest/minetest.conf
      - ./server/mods:/config/.minetest/mods
      - ./server/worlds:/config/.minetest/worlds
      - ./server/games:/config/.minetest/games
      - ./server/backups:/backups
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - CLI_ARGS=--worldname world
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -tulpn | grep :30000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - luanti-network

  # Backup service opcional con n8n integration
  backup-cron:
    image: alpine:latest
    container_name: luanti-voxelibre-backup
    restart: unless-stopped
    volumes:
      - ./server/worlds:/worlds:ro
      - ./server/backups:/backups
      - ./scripts:/scripts:ro
    environment:
      - TZ=America/Santiago
    command: >
      sh -c "
        apk add --no-cache dcron tar gzip findutils &&
        echo '0 */6 * * * sh /scripts/backup.sh' > /tmp/crontab.txt &&
        echo '0 3 * * * sh /scripts/rotate-backups-container.sh' >> /tmp/crontab.txt &&
        crontab /tmp/crontab.txt &&
        crond -f -d 8
      "
    depends_on:
      - luanti-server
    networks:
      - luanti-network

  # Discord notifier - Notificaciones de conexiones de jugadores
  discord-notifier:
    image: alpine:latest
    container_name: luanti-discord-notifier
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/scripts:ro
    environment:
      - TZ=America/Santiago
      - CONTAINER_NAME=luanti-voxelibre-server
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    command: >
      sh -c "
        apk add --no-cache curl docker-cli bash &&
        bash /scripts/discord-notifier.sh
      "
    depends_on:
      - luanti-server
    networks:
      - luanti-network

networks:
  luanti-network:
    driver: bridge
